.TH "salad" 1 "Wed Dec 25 2013" "Letter Salad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
salad \- A Content Anomaly Detector Based on n-Grams 

.br
 
.SH "SYNOPSIS"
.PP
salad [<mode>] [options]
.SH "DESCRIPTION"
.PP
\fBLetter\fP \fBSalad\fP or \fBSalad\fP for short, is an efficient and flexible implementation of the well-known anomaly detection method Anagram by Wang et al (RAID 2006)\&.
.PP
\fBSalad\fP enables detecting anomalies in large-scale string data\&. The tool is based on the concepts of n-grams, that is, strings are compared using all substrings of length n\&. During training, cf\&. \fBsalad-train\fP(1), these n-grams are extracted from a collection of strings and stored in a Bloom filter\&. This enables the detector to represent a large number of n-grams in very little memory\&. During anomaly detection, the n-grams of unknown strings are matched against the Bloom filter and strings containing several n-grams not seen during training are flagged as anomalous\&.
.PP
\fBSalad\fP extends the original method Anagram in different ways: First, the tool does not only operate on n-grams of bytes, but is also capable of comparing n-grams over words and tokens\&. Second, \fBSalad\fP implements a 2-class version of the detector that enables discriminating strings of two types, cf\&. \fBsalad-predict\fP(1) for more details\&. Finally, the tool features a build-in inspection and statistic mode that can help to analyze the learned Bloom filter and its predictions, cf\&. \fBsalad-inspect\fP(1) and \fBsalad-stats\fP(1) respectively\&.
.PP
The tool can be utilized in different fields of application\&. For example, the concept underlying \fBSalad\fP has been prominently used for intrusion detection, but is not limited to this scenario\&. 
.SH "OPTIONS"
.PP
The options depend on the provided mode of operation\&. If no mode is specified, the following generic options are available:
.PP
\fB--help\fP
.RS 4
Print the help screen\&. 
.RE
.PP
\fB--version\fP
.RS 4
Print version and copyright\&.
.RE
.PP
.SH "MODES"
.PP
There exist two different means of accessing salad's modes: (1) As command line option to the main executable, or (2) as stand-alone executable prefixed with \fBsalad-\fP\&.
.PP
The following list contains the names of the stand-alone executables, for which individual man pages are available:
.SS "salad-train(1)"
Trains the anomaly detector\&.
.SS "salad-predict(1)"
Predicts the anomaly score of the specified data\&.
.SS "salad-stats(1)"
Provides statistical information of a trained anomaly detector\&.
.SS "salad-inspect(1)"
Analyzes the specified data with respect to the n-gram model used by the detector\&.
.SH "COPYRIGHT"
.PP

.br
 
.PP
Copyright (c) 2012-2013, Christian Wressnegger
.br
 All rights reserved\&.
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&. 
