.TH "salad-stats" 1 "Tue Dec 17 2013" "Letter Salad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
salad-stats \- Statistics mode of Salad 

.br
 
.SH "SYNOPSIS"
.PP
salad stats [options]
.SH "DESCRIPTION"
.PP
Provides statistical information of the specified Bloom filter\&. In particular this currently is limited to the filter's saturation\&.
.SH "OPTIONS"
.PP
.SS "I/O Options:"
\fB-b, --bloom <file>\fP
.RS 4
The bloom filter to be analyzed\&.
.RE
.PP
.SS "Generic Options:"
\fB-h, --help\fP
.RS 4
Print the help screen\&.
.RE
.PP
.SH "COPYRIGHT"
.PP
Copyright (c) 2012-2013, Christian Wressnegger
.br
 All rights reserved\&.
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&. 
