function(find_veggiebed var base)
	set(C 0)
	set(MAX_DEPTH 10)

	set(DIR "${base}")
	while (NOT EXISTS "${DIR}/BASE" AND C LESS MAX_DEPTH)
		set(DIR "${DIR}/..")
		get_filename_component(DIR "${DIR}" REALPATH)
		MATH(EXPR C "${C}+1")
	endwhile ()

	if (C LESS MAX_DEPTH)
		set("${var}" "${DIR}" PARENT_SCOPE)
	else()
		set("${var}" "${base}" PARENT_SCOPE)
	endif()
endfunction ()
